spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost/socialmanagement
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8081
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173

jwt.secret=cee0cc013561d20092149bc327186e116549a6a1d313b94886eb2b7b5cc1b4d7ab13dd2387f5084fb2ab35978c49888e6c3b5a03e8698af1bea34b40e2ae9c70
jwt.accesstoken.expiration=900
jwt.refreshtoken.expiration=604800
app.cookie.secure=false

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=60000


# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nhatnam201104@gmail.com
spring.mail.password=akue gnno rlqo yorp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OTP
app.otp.expiration-seconds=300
app.otp.cooldown-seconds=60
